DELETE http://localhost:3003/api/blogs/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV1c2VyaSIsImlkIjoiNjFlNTUyNWNkNGQ5ZmY3ZTljY2Q3N2UyIiwiaWF0IjoxNjQyNDE4Nzk4fQ.A4V6a7L9bi42tZZitpDmod2sJ6lotjlj79aYxpteNlc