DELETE http://localhost:3003/api/blogs/61ee9db5a7dd2c8c68f8c5d5
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV1c2VyaSIsImlkIjoiNjFlNTUyNWNkNGQ5ZmY3ZTljY2Q3N2UyIiwiaWF0IjoxNjQzMDI4NjY1fQ.q3sUGqkSKkWf0hhdsUs5-fN6zi4VtsEPhCVtDcyS6zY