POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjYxZDQyYWJhNTVlNWI4Mzg5ODc4YzQxOSIsImlhdCI6MTY0MTM4NTc0M30.fl3Jce6Fk_CB2vMPS8hUzZzMTZ18X84we_Lw4lQEuFI

{
  "title": "blogi3",
  "author": "blogimies",
  "url": "http://blogi",
  "likes": 61
  


}